### PR TITLE
Placeholder fix & .gitignore added

### PR DESCRIPTION
**Pull request by webtrix**
On the demo-page, when you add a very large `margin-top` on the `<div class="demo">` element and you scroll down you won't be able anymore to drag & drop an element to the top of the dragster-region.

Only if you put the scrollbar all the way to the top, this issue is resolved, but not when the scrollbar isn't at the top. This fix, solves this issue.

### CODE REVIEW

**Comment by webtrix** [comment]
Done!

**Comment by sunpietro** [comment]
@webtrix can you run `git rebase -i HEAD~4` in your terminal, please? It allow you to remove the commits with addition/removal of `.gitignore` file. You should have only 2 commits in the end :)

**Comment by webtrix** [comment]
Hmm.. did something wrong, will create a new PR, sorry.

**Comment by webtrix** [comment]
OK, this explains. I was using the latest tag (1.3.2) version of you code, and not the code of you master branch. The code in your master branch also fixes the problem.

Maybe create a new tag? :-)

**Pull request closed without merging**
