### PR TITLE
Fixed: issue with dragster-placeholder 

### PR DESCRIPTION
**Pull request by webtrix**
On the demo-page, when you add a very large `margin-top` on the `<div class="demo">` element and you scroll down you won't be able anymore to drag & drop an element to the top of the dragster-region.

### CODE REVIEW

**Comment by webtrix** [comment]
FYI: I would create a new tag (if possible), because before I was working with the code of the 1.3.2-tag, that's available via NPM, but the master branch code is totally different from the 1.3.2-tag version.

**Comment by sunpietro** [comment]
@webtrix if master code is ok and doesn't require your fix, then I will create a new tag later today.
In that case, close your PR, please :)

**Comment by webtrix** [comment]
Master code has the same problem sadly.

**Comment by sunpietro** [comment]
Thank you for you PR. Good job! 👍

**Comment by sunpietro** [comment]
The NPM has been updated.

**Pull request merged**
